return {
  { import = 'plugins.coding.ai' },
  { import = 'plugins.coding.completion' },
  { import = 'plugins.coding.editing' },
  { import = 'plugins.coding.formatting' },
  { import = 'plugins.coding.linting' },
  { import = 'plugins.editor.diagnostics' },
  { import = 'plugins.editor.filetree' },
  { import = 'plugins.editor.navigation' },
  { import = 'plugins.editor.fzf' },
  { import = 'plugins.editor.tools' },
  { import = 'plugins.editor.treesitter' },
  { import = 'plugins.ui.breadcrumbs' },
  { import = 'plugins.ui.bufferline' },
  { import = 'plugins.ui.indent' },
  { import = 'plugins.ui.misc' },
  { import = 'plugins.ui.notify' },
  { import = 'plugins.ui.statusline' },
  { import = 'plugins.tools.git' },
  { import = 'plugins.tools.misc' },
}
